horror_movie/config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :user,
    path: 'public',
    controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  root :to => "public/homes#top"
  get '/admin' => 'admin/homes#top', as: 'admin'
  get '/about' => 'public/homes#about', as: 'about'

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :movies, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :comments, only: [:destroy]
  end

  namespace :public do
    resources :movies, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :comments, only: [:create, :destroy]

  end
    resource :users,only: []
    get '/my_page' => 'users#show'
    get '/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/unsubscribe'
    patch 'users/withdraw'
  end





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

horror_movie/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

horror_movie/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached :image
end

horror_movie/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  
  validates :comment, presence: true
end

horror_movie/app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie, dependent: :destroy
end

horror_movie/app/models/movie.rb
class Movie < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :genre
  
  validates :title, presence: true
  validates :year, presence: true
  validates :director, presence: true
  validates :watch, presence: true
  validates :rate, presence: true
  validates :rate_horror, presence: true
end

horror_movie/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :comments, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, presence: true
  validates :email, presence: true
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

end

horror_movie/app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
    
  def destroy
    Comment.find(params[:id]).destroy
    redirect_to admin_users_path
  end
  
end

horror_movie/app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

horror_movie/app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genres = Genre.all
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.delete
    redirect_to admin_genres_path
  end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

horror_movie/app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
  def index
  end

  def show
  end
  
  def destroy
    @movie = Movie.find(params[:id])
    @movie.delete
    redirect_to admin_users_path
  end
end

horror_movie/app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

horror_movie/app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  protected
  def after_sign_in_path_for(resource)
    admin_genres_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

horror_movie/app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

horror_movie/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @movies = @user.movies.page(params[:page])
    @comments = @user.comments.page(params[:page])
  end

  def edit
  end
  
end

horror_movie/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   #before_action :authenticate_user!, except: [:top, :about]
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

horror_movie/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

horror_movie/app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

horror_movie/app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

horror_movie/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

horror_movie/app/helpers/application_helper.rb
module ApplicationHelper
end

horror_movie/app/views/admin/new.html.erb
<h2>Resend confirmation instructions</h2>

<%= form_for(resource, as: resource_name, url: confirmation_path(resource_name), html: { method: :post }) do |f| %>
  <%= render "admins/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email) %>
  </div>

  <div class="actions">
    <%= f.submit "Resend confirmation instructions" %>
  </div>
<% end %>

<%= render "admins/shared/links" %>

horror_movie/app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

horror_movie/app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

horror_movie/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HorrorMovie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class= "navbar navbar-expand-lg navbar-light" style= "background-color: black">
        <div class= "container">
          <%= link_to root_path, class: "navbar-brand p-3, btn btn-light" do %>
            <i class="fas fa-film"></i>
            ジャンル一覧
          <% end %>
          <div>
            <ul class= "navbar-nav ml-auto">
              <% if user_signed_in? %>
                <p><font color="red">
                  <%= current_user.name %>,
                  Welcome to World of Horror
                  </font>
                </p>
                <li class= "nav-item pl-3">
                  <%= link_to public_my_page_path, class: 'nav-link text-dark' do %>
                    <button type= "button" class= "btn btn-light"><i class="fas fa-user-tie"></i>マイページ</button>
                  <% end %>
                </li>
                <li class= "nav-item pl-3">
                  <%= link_to about_path, class: 'nav-link text-dark' do %>
                    <button type= "button" class= "btn btn-light"><i class="fas fa-question-circle"></i>About</button>
                  <% end %>
                </li>
                <li class= "nav-item pl-3">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
                    <button type= "button" class= "btn btn-light"><i class="fas fa-sign-out-alt"></i>ログアウト</button>
                  <% end %>
                </li>

              <% elsif admin_signed_in? %>
                <li class= "nav-item pl-3">
                  <%= link_to admin_movies_path, class: 'nav-link text-dark' do %>
                    <button type= "button" class= "btn btn-light"><i class="far fa-file-video"></i>映画一覧</button>
                  <% end %>
                </li>
                <li class= "nav-item pl-3">
                  <%= link_to admin_genres_path, class: 'nav-link text-dark' do %>
                  <button type= "button" class= "btn btn-light"><i class="fab fa-optin-monster"></i>ジャンル一覧</button>
                <% end %>
                </li>
                <li class= "nav-item pl-3">
                  <%= link_to admin_users_path, class: 'nav-link text-dark' do %>
                    <button type= "button" class= "btn btn-light"><i class="fas fa-users"></i>会員一覧</button>
                  <% end %>
                </li>
                <li class= "nav-item pl-3">
                  <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
                    <button type= "button" class= "btn btn-light"><i class="fas fa-sign-out-alt"></i>ログアウト</button>
                  <% end %>
                </li>

              <% else %>
                <li class= "nav-item pl-3">
                  <%= link_to about_path, class: 'nav-link text-dark' do %>
                    <button type= "button" class= "btn btn-light"><i class="fas fa-question-circle"></i>About</button>
                  <% end %>
                </li>
                <li class= "nav-item pl-3">
                  <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                    <button type= "button" class= "btn btn-light"><i class="fas fa-user-plus"></i>新規登録</button>
                  <% end %>
                </li>
                <li class= "nav-item pl-3">
                  <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
                    <button type= "button" class= "btn btn-light"><i class="fas fa-sign-in-alt"></i>ログイン</button>
                  <% end %>
                </li>
              <% end %>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer class="bottom: 0">
      <nav class= "navbar navbar-expand-lg navbar-light" style= "background-color: black">
        <p class="px-5 mx-auto text-danger">
          How much fear do you know?
        </p>
      </nav>
    </footer>
  </body>
  
</html>