horror_movie/config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :user,
    path: 'public',
    controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  root :to => "public/homes#top"
  get '/admin' => 'admin/homes#top', as: 'admin'
  get '/about' => 'public/homes#about', as: 'about'

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :movies, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :comments, only: [:destroy]
  end

  namespace :public do
    resources :movies, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :comments, only: [:create, :destroy]

  end
    resource :users,only: []
    get '/my_page' => 'users#show'
    get '/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/unsubscribe'
    patch 'users/withdraw'
  end





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

horror_movie/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :comments, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, presence: true
  validates :email, presence: true
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

end

horror_movie/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @movies = @user.movies.page(params[:page])
    @comments = @user.comments.page(params[:page])
  end

  def edit
  end
  
end

horror_movie/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

horror_movie/app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

horror_movie/app/views/admin/users/index.html.erb
<div class="container">
  <div class="row py-4">
    <div clsss="offset-1">
      <h4>登録ユーザー一覧</h4>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-10">
      <table class="table table-hover table-inverse">
          <tr>
            <th>ユーザーID</th>
            <th>プロフィール画像</th>
            <th>ユーザー名</th>
            <th>投稿映画本数</th>
            <th>投稿コメント数</th>
          </tr>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= image_tag user.get_profile_image, size:"50x50" %></td>
            <td><%= link_to user.name, admin_user_path(user.id) %></td>
            <td><%= user.movies.count %>タイトル</td>
            <td><%= user.comments.count %>コメント</td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center"><%= paginate @users %></div>
    </div>
  </div>
</div>

horror_movie/app/views/admin/users/show.html.erb
<div class="container">
  <div class="row py-4">
    <div clsss="offset-1">
      <h4><strong><%= @user.name %></strong>さんの詳細</h4>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
     <div class="col-md-2">
       <table>
         <tr><%= image_tag @user.get_profile_image, size:"100x100" %></tr>
           <th>ユーザー名</th>
             <tr>
               <td><%= @user.name %></td>
             </tr>
      　    <th>メールアドレス</th>
      　      <tr>
           　   <td><%= @user.email %></th>
             </tr>
       </table>
     </div>
       <div class="col-md-5">
         <table class="table table-hover table-inverse">
           <tr>
             <th>投稿映画一覧</th>
             <th></th>
           </tr>
           <tbody>
             <% @movies.each do |movie| %>
             <tr>
               <td><%= movie.title %></td>
               <td><%= link_to '削除する', admin_movie_path(movie), method: :delete, class: 'btn btn-sm btn-danger' %></td>
             </tr>
             <% end %>
           </tbody>
         </table>
          <div class="d-flex justify-content-center"><%= paginate @movies %></div>
       </div>
       <div class="col-md-5">
         <table class="table table-hover table-inverse">
           <tr>
             <th>投稿コメント一覧</th>
             <th></th>
           </tr>
           <tbody>
             <% @comments.each do |comment| %>
             <tr>
               <td><%= comment.comment %></td>
               <td><%= link_to '削除する', admin_comment_path(comment), method: :delete, class: 'btn btn-sm btn-danger' %></td>
             </tr>
             <% end %>
           </tbody>
         </table>
          <div class="d-flex justify-content-center"><%= paginate @comments %></div>
       </div>
  </div>
</div>